version: '3'
services:
  mysql1:
    image: mysql:5.7.26
    restart: always
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: a1234
      TZ: Asia/Shanghai
    ports:
      - 13306:3306
    volumes:
      - /usr/local/docker/mysql/data1:/var/lib/mysql/data
      - /usr/local/docker/mysql/my1.cnf:/etc/mysql/my.cnf
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password

  mysql2:
    image: mysql:5.7.26
    restart: always
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: a1234
      TZ: Asia/Shanghai
    ports:
      - 13307:3306
    volumes:
      - /usr/local/docker/mysql/data2:/var/lib/mysql/data
      - /usr/local/docker/mysql/my2.cnf:/etc/mysql/my.cnf
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password

  mysql3:
    image: mysql:5.7.26
    restart: always
    container_name: mysql3
    environment:
      MYSQL_ROOT_PASSWORD: a1234
      TZ: Asia/Shanghai
    ports:
      - 13308:3306
    volumes:
      - /usr/local/docker/mysql/data3:/var/lib/mysql/data
      - /usr/local/docker/mysql/my3.cnf:/etc/mysql/my.cnf
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password